---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: frontend-image
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/rhtedemo5/frontend
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: frontend-git
spec:
  type: git
  params:
  - name: url
    value: https://github.com/piggyvenus/rhtedemo5
